version: '3.9'

services:
  mssqlscripts:
    container_name: KeycloakSqlScript
    image: mcr.microsoft.com/mssql-tools
    command: /bin/bash -c 'until /opt/mssql-tools/bin/sqlcmd -S host.docker.internal -U sa -P Aa123456789*-+ -Q "create database KeycloakDb"; do sleep 5; done'
    network_mode: bridge

  keycloak:
    container_name: Keycloak
    restart: always
    build:
      context: .
      dockerfile: src/Inventory/Keycloak/MsSql/Dockerfile
      args:
        KEYCLOAK_VERSION: latest
    command: ['start', '--optimized']
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB_URL: jdbc:sqlserver://host.docker.internal;databaseName=KeycloakDb;encrypt=false
      KC_DB_USERNAME: sa                                              # database server user
      KC_DB_PASSWORD: Aa123456789*-+                                  # database server password
      KC_DB: mssql
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_PROXY: passthrough
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_URL: 'http://localhost:4000'
      KC_HTTPS_CERTIFICATE_FILE: /etc/x509/https/docker-host.crt      # host.docker.internal SSL
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/x509/https/docker-host.key  # host.docker.internal SSL
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'Aa123456789*-+'
    ports:
      - "4000:8080" # localhost ssl port 4000 yapilacak
      #- "4000:8081"# localhost ssl port: 8443
    volumes:
      - ./src/Inventory/Keycloak/MsSql/ssl:/etc/x509/https
    depends_on:
      - mssqlscripts
    network_mode: bridge

  redis:
    container_name: Redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=Aa123456789*-+
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    network_mode: bridge

  mssql:
    container_name: MsSqlServer2022
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Aa123456789*-+"
    ports:
      - 1433:1433
    network_mode: bridge

  serilogseq:
    container_name: SerilogSeq
    image: datalust/seq:latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - 5341:80
    network_mode: bridge
    depends_on:
      - mssql

    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: RabbitMQ
    ports:
        - 5672:5672
        - 15672:15672
    environment:
        RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
        RABBITMQ_DEFAULT_USER: "rabbitmq"
        RABBITMQ_DEFAULT_PASS: "Aa123456789*-+"
        RABBITMQ_DEFAULT_VHOST: "/"
    network_mode: bridge
    restart: always


  InventoryManagementApi:
    image: ${DOCKER_REGISTRY-}inventorymanagementapi
    container_name: "InventoryManagementApi"
    restart: "always"
    ports:
      - "4001:8080"
    build:
      context: .
      dockerfile: src/Inventory/Backend/WebAPI/Web.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl/aspnetapp.pfx
      
      - ConnectionStrings__SqlServerConnection=Server=host.docker.internal,1433;Database=IMDB;User=sa;Password=Aa123456789*-+;TrustServerCertificate=True
      - ConnectionStrings__CapLogSqlServerConnection=Server=host.docker.internal,1433;Database=CapLog;User=sa;Password=Aa123456789*-+;TrustServerCertificate=True
      - ConnectionStrings__SeriLogConnection=Server=host.docker.internal,1433;Database=NlogDb;User=sa;Password=Aa123456789*-+;TrustServerCertificate=True
     
      - RedisConnectionSettings__RedisURL=host.docker.internal
      - RedisConnectionSettings__PreferRedis=false
      - RedisConnectionSettings__Port=6379
      - RedisConnectionSettings__Database=0
      - RedisConnectionSettings__DefaultExpiration=00:01:00

      - RabbitMQ__Host=host.docker.internal
      - RabbitMQ__Username=rabbitmq
      - RabbitMQ__Password=Aa123456789*-+
      - RabbitMQ__Port=5672

      - SerilogSeqUrl=http://seq:5341/
      - Serilog__MinimumLevel__Default=Warning

      - Keycloak__Authority=http://host.docker.internal:4000/realms/inventory_management_realm
      - Keycloak__Audience=InventoryManagementClient
      - Keycloak__KeycloakResourceUrl=http://host.docker.internal:4000/realms/inventory_management_realm/authz/protection/resource_set/
      - Keycloak__ClientCredentialsTokenAddress=http://host.docker.internal:4000/realms/inventory_management_realm/protocol/openid-connect/token
    volumes:
      - ./src/Inventory/Backend/WebAPI/Web.API/ssl:/app/ssl
    depends_on:
      - keycloak
      - mssql
      - rabbitmq
      - redis
    network_mode: bridge


  InventoryManagementFrontend:
    image: ${DOCKER_REGISTRY-}inventorymanagementfrontend
    container_name: "InventoryManagementFrontend"
    restart: "always"
    ports:
      - "4002:8081"
    build:
      context: .
      dockerfile: src/Inventory/Frontend/InventoryManagement.Frontend/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081

      - InventoryManagementApi=http://host.docker.internal:4001

      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/ssl/aspnetapp.pfx

      - Keycloak__KeycloakEndpoint=http://host.docker.internal:4000
      - Keycloak__ClientId=InventoryManagementClient
      - Keycloak__ClientSecret=Zs6XKKBjBple3OJJPLsZpK5M7MmD1TFn
      - Keycloak__GrantType=password
      - Keycloak__Audience=InventoryManagementClient
      - Keycloak__Realm=InventoryManagementClient
      - Keycloak__RealmId=inventory_management_realm
      - Keycloak__GrantTypePermissions=urn:ietf:params:oauth:grant-type:uma-ticket
    depends_on:
      - InventoryManagementApi
    volumes:
      - ./src/Inventory/Frontend/InventoryManagement.Frontend/ssl:/app/ssl
      - ./src/Inventory/Frontend/InventoryManagement.Frontend/Reports:/app/Reports
    network_mode: bridge


volumes:
  keycloak_data_cert:
